name: space_news
description: Space Curiosity and all the things realted to the final frontier.

dependencies:
  flutter:
    sdk: flutter

  ## Online
  cloud_firestore: 0.8.1
  webfeed: ^0.4.1
  http: ^0.12.0
  flutter_web_browser: ^0.9.0+1

  ## Offline
  cached_network_image: ^0.5.1

  ## Tools
  dynamic_theme: ^1.0.0
  scoped_model: ^1.0.1
  intl: ^0.15.7
  flutter_swiper: ^1.1.4
  sliver_fab: ^0.1.1
  clipboard_manager: ^0.0.4
  image_downloader: ^0.9.1
  add_2_calendar: ^1.0.2
  flutter_map: ^0.3.0
  share: ^0.5.3
  # UPDATE KOTLIN VERSION
  # get_version: ^0.0.5
  native_widgets: ^0.1.1+1
  flutter_i18n: ^0.5.0
  material_search: ^0.2.8
  location: ^1.4.1

  ## Icons
  font_awesome_flutter: ^8.2.0
  cupertino_icons: ^0.1.2

  ## Future
  # flutter_cupertino_settings: ^0.0.8
  # dynamic_theme:
  #   git:
  #     url: git://github.com/Norbert515/dynamic_theme.git

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700
  assets:
    - assets/flutter_i18n/

  uses-material-design: true