name: space_news
description: Spark your curiosity

version: 1.1.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  cloud_firestore: ^0.9.5+2
  dio: ^2.1.3
  flutter_mailer: ^0.4.1
  flutter_web_browser: ^0.11.0
  webfeed: ^0.4.2

  ## Offline
  cached_network_image: ^0.7.0
  shared_preferences: ^0.5.2

  ## Widgets
  app_review: ^0.1.0
  add_2_calendar: ^1.2.2
  flutter_local_notifications: ^0.7.1+1
  flare_flutter: ^1.3.0
  flutter_map: ^0.5.0+1
  flutter_swiper: ^1.1.6
  material_search: ^0.2.8
  native_widgets: ^0.1.1+1
  persist_theme: ^0.0.3+6
  row_collection: ^0.2.1
  sliver_fab: ^1.0.0

  ## Tools
  clipboard_manager: ^0.0.4
  equatable: ^0.2.2
  flutter_bloc: ^0.6.2
  flutter_i18n: ^0.6.3
  image_downloader: ^0.11.1
  location: ^2.0.0
  package_info: ^0.4.0+1
  recase: ^2.0.1
  quick_actions: ^0.3.0+1
  scoped_model: ^1.0.1
  share: ^0.6.0+1

  ## Icons
  font_awesome_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700
  assets:
    - assets/flutter_i18n/
    - assets/animations/
    - assets/icons/android/

  uses-material-design: true
