name: space_news
description: Space news

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model: 0.2.0
  redux: 3.0.0
  flutter_redux: 0.5.1
  firebase_database: 0.4.6
  cloud_firestore: 0.7.3
  http: 0.11.3+17
  intl: "^0.15.6"
  url_launcher: "^3.0.2"
  flutter_web_browser: "^0.9.0+1"
  material_search: ^0.2.7
  share: "^0.4.0"
  device_info: "^0.2.0"
  firebase_core: "^0.2.3"
  firebase_analytics: "^0.3.0"
  # firebase_admob: ^0.5.0
  font_awesome_flutter: 6.0.0
  firebase: '^4.3.0'
  get_version: 0.0.5
  native_widgets: ^0.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Light.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700

  uses-material-design: true